const projects = [
    {ProjectName: "Project Homeroom",
    GitHub: "https://github.com/AWinterCoding/Project_Home_Room",
VideoLink: "#",
DeployedApplication: "https://homeroom-app-4000de1bd278.herokuapp.com/"},
    {ProjectName: "Project United",
    GitHub: "https://github.com/Childofrainydays/project-united",
VideoLink: "#",
DeployedApplication: "https://project-united.herokuapp.com/"},
    {ProjectName: "Password Generator",
         GitHub: "https://github.com/AWinterCoding/Auto-Password-Generator",
          VideoLink: "#",
           DeployedApplication: "https://awintercoding.github.io/Auto-Password-Generator/"
        },
    {ProjectName: "Weather Application",
    GitHub: "https://github.com/AWinterCoding/WeatherApplication",
VideoLink: "#",
DeployedApplication: "https://awintercoding.github.io/WeatherApplication/"},
{ProjectName: "Simple Logo Generator",
    GitHub: "https://github.com/AWinterCoding/SimpleLogoGenerator",
VideoLink: "https://drive.google.com/file/d/1pPlsMVNqX4jyioD-ifAtPilrjMDo-KoH/view",
DeployedApplication: "#"},
{ProjectName: "Company CMS Database",
    GitHub: "https://github.com/AWinterCoding/Company_CMS_Database",
VideoLink: "https://drive.google.com/file/d/1o6O7Xe68_5F8X6m04mS4GKcBlFNQ0cNn/view",
DeployedApplication: "#"},
{ProjectName: "Social Media API",
    GitHub: "https://github.com/AWinterCoding/SocialMediaAPI",
VideoLink: "https://drive.google.com/file/d/1SLtw-Hy93zkLi-ZHHx-hixWtHrhkJxth/view",
DeployedApplication: "#"},
{ProjectName: "README Generator",
    GitHub: "https://github.com/AWinterCoding/README_Generator",
VideoLink: "#",
DeployedApplication: "#"},
{ProjectName: "Ecommerce Sequelize",
    GitHub: "https://github.com/AWinterCoding/ECommerceSequelize",
VideoLink: "https://drive.google.com/file/d/1iSsnTsUPjQxp8ixdSJNrFWW8f1Y8T1FW/view",
DeployedApplication: "#"},
{ProjectName: "Programming Blog",
    GitHub: "https://github.com/AWinterCoding/ProgrammingBlog",
VideoLink: "#",
DeployedApplication: "https://programming-blog-mvc-41e288a7da24.herokuapp.com/"},
];

export default projects;